name: ${name}
version: ${version}
main: ${main}
authors: [ NextdoorPsycho, Vatuu ]
website: github.com/TimelostSoftware
api-version: ${apiversion}
commands:
  vault:
    description: "A Timeless Vault"
    usage: /<command>
    permission: timevault.open